// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "sources.pubmed.enabled": boolean;
      "sources.openalex.enabled": boolean;
      "sources.crossref.enabled": boolean;
      "sources.semanticscholar.enabled": boolean;
      "maxResults": number;
      "searchDialogWidth": number;
      "searchDialogHeight": number;
      "defaultYearFilter": string;
      "openAccessOnly": boolean;
      "cacheEnabled": boolean;
      "cacheTTLHours": number;
    };
  }
}
